use assert_cmd::Command;
use predicates::prelude::*;
use serde_json::Value;

fn write_cache(root: &std::path::Path, dir: &str, build_type: &str, generator: &str) {
    write_cache_with_prefix(root, dir, build_type, generator, "");
}

fn write_vs_cache(root: &std::path::Path, dir: &str, build_type: &str, generator: &str) {
    write_cache_with_prefix(
        root,
        dir,
        build_type,
        generator,
        "# It was generated by CMake: C:/Program Files/Microsoft Visual Studio/18/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe\n",
    );
}

fn write_cache_with_prefix(
    root: &std::path::Path,
    dir: &str,
    build_type: &str,
    generator: &str,
    prefix: &str,
) {
    let build_dir = root.join(dir);
    std::fs::create_dir_all(&build_dir).expect("build dir");
    let home = root.canonicalize().expect("canonical root");
    std::fs::write(
        build_dir.join("CMakeCache.txt"),
        format!(
            "{prefix}CMAKE_BUILD_TYPE:STRING={build_type}\nCMAKE_GENERATOR:INTERNAL={generator}\nCMAKE_HOME_DIRECTORY:INTERNAL={}\n",
            home.display()
        ),
    )
    .expect("write cache");
}

#[test]
fn doctor_no_probe_json_reports_project_and_profile() {
    let temp = tempfile::tempdir().expect("tempdir");
    std::fs::write(
        temp.path().join("CMakeLists.txt"),
        "cmake_minimum_required(VERSION 3.20)\n",
    )
    .expect("write CMakeLists");
    std::fs::write(
        temp.path().join(".qtflow.toml"),
        r#"
default_profile = "release"

[profiles.release]
preset = "Qt-Release-Custom"
build_dir = "build/release"
"#,
    )
    .expect("write config");

    let output = Command::cargo_bin("qtflow")
        .expect("binary")
        .env_remove("QTFLOW_CONFIG")
        .env_remove("QTFLOW_PROFILE")
        .env_remove("QTFLOW_CMAKE")
        .env_remove("QTFLOW_CTEST")
        .env_remove("QTFLOW_NINJA")
        .env_remove("QTFLOW_QMAKE")
        .env_remove("QTFLOW_VSDEVCMD_BAT")
        .env_remove("VSDEVCMD_BAT")
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["doctor", "--no-probe", "--json"])
        .assert()
        .success()
        .stdout(predicate::str::contains("\"profile\""))
        .get_output()
        .stdout
        .clone();

    let json: Value = serde_json::from_slice(&output).expect("valid JSON");
    let actual_root = std::path::Path::new(json["projectRoot"].as_str().expect("projectRoot"))
        .canonicalize()
        .expect("canonical actual root");
    assert_eq!(
        actual_root,
        temp.path().canonicalize().expect("canonical temp")
    );
    assert_eq!(json["profile"], "release");
    assert_eq!(json["buildSystem"], "cmake");
    assert_eq!(
        json["selectedProfile"]["preset"],
        Value::String("Qt-Release-Custom".to_string())
    );
    for pointer in [
        "/projectRoot",
        "/configFile",
        "/configSource",
        "/selectedProfile/buildDir",
    ] {
        let value = json.pointer(pointer).and_then(Value::as_str).unwrap();
        assert!(
            !value.contains('\\'),
            "{pointer} should use forward slashes: {value}"
        );
    }
}

#[test]
fn doctor_no_probe_json_reports_qmake_section_for_qmake_project() {
    let temp = tempfile::tempdir().expect("tempdir");
    std::fs::write(temp.path().join("app.pro"), "TEMPLATE = app\n").expect("write pro");
    std::fs::write(
        temp.path().join(".qtflow.toml"),
        r#"
build_system = "qmake"

[qmake]
qmake = "qmake-stub"
spec = "linux-g++"
make = "make"

[msvc]
enabled = false

[profiles.debug]
build_dir = "out/build/debug"
"#,
    )
    .expect("write config");

    let output = Command::cargo_bin("qtflow")
        .expect("binary")
        .env_remove("QTFLOW_CONFIG")
        .env_remove("QTFLOW_PROFILE")
        .env_remove("QTFLOW_CMAKE")
        .env_remove("QTFLOW_CTEST")
        .env_remove("QTFLOW_NINJA")
        .env_remove("QTFLOW_QMAKE")
        .env_remove("QTFLOW_VSDEVCMD_BAT")
        .env_remove("VSDEVCMD_BAT")
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["doctor", "--no-probe", "--json"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();

    let json: Value = serde_json::from_slice(&output).expect("valid JSON");
    assert_eq!(json["buildSystem"], "qmake");
    assert_eq!(json["qmake"]["path"], "qmake-stub");
    assert_eq!(json["qmake"]["status"], "notProbed");
    assert_eq!(json["qmake"]["source"], "config");
    assert_eq!(json["qmake"]["spec"], "linux-g++");
    assert_eq!(json["qmake"]["make"], "make");
    assert!(json["qmake"].get("version").is_none());
}

#[test]
fn doctor_json_reports_presets_and_missing_probe_status() {
    let temp = tempfile::tempdir().expect("tempdir");
    std::fs::write(
        temp.path().join("CMakeLists.txt"),
        "cmake_minimum_required(VERSION 3.20)\n",
    )
    .expect("write CMakeLists");
    std::fs::write(
        temp.path().join("CMakePresets.json"),
        r#"{"version": 6, "configurePresets": [{"name": "Qt-Debug"}]}"#,
    )
    .expect("write presets");
    std::fs::write(
        temp.path().join(".qtflow.toml"),
        r#"
[tools]
cmake = "definitely-missing-cmake-for-doctor"
ctest = "definitely-missing-ctest-for-doctor"
ninja = "C:/tools/ninja.exe"

[msvc]
enabled = false

[profiles.debug]
preset = "Qt-Debug"
build_dir = "out/build/debug"
"#,
    )
    .expect("write config");

    let output = Command::cargo_bin("qtflow")
        .expect("binary")
        .env_remove("QTFLOW_CONFIG")
        .env_remove("QTFLOW_PROFILE")
        .env_remove("QTFLOW_CMAKE")
        .env_remove("QTFLOW_CTEST")
        .env_remove("QTFLOW_NINJA")
        .env_remove("QTFLOW_QMAKE")
        .env_remove("QTFLOW_VSDEVCMD_BAT")
        .env_remove("VSDEVCMD_BAT")
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["doctor", "--json"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();

    let json: Value = serde_json::from_slice(&output).expect("valid JSON");
    assert_eq!(json["cmake"]["status"], "notFound");
    assert_eq!(json["ctest"]["status"], "notFound");
    assert_eq!(json["ninja"]["path"], "C:/tools/ninja.exe");
    assert_eq!(json["ninja"]["status"], "found");
    assert_eq!(json["ninja"]["source"], "config");
    assert_eq!(json["cmakePresets"], serde_json::json!(["Qt-Debug"]));
}

#[test]
fn doctor_no_probe_json_reports_discovered_build_dirs_with_roles() {
    let temp = tempfile::tempdir().expect("tempdir");
    std::fs::write(
        temp.path().join("CMakeLists.txt"),
        "cmake_minimum_required(VERSION 3.20)\n",
    )
    .expect("write CMakeLists");
    write_cache(temp.path(), "build", "Debug", "Ninja");
    write_cache(temp.path(), "build-release", "Release", "Ninja");
    write_cache(
        temp.path(),
        "build/_deps/googletest-subbuild",
        "Debug",
        "Ninja",
    );

    let output = Command::cargo_bin("qtflow")
        .expect("binary")
        .env_remove("QTFLOW_CONFIG")
        .env_remove("QTFLOW_PROFILE")
        .env_remove("QTFLOW_CMAKE")
        .env_remove("QTFLOW_CTEST")
        .env_remove("QTFLOW_NINJA")
        .env_remove("QTFLOW_QMAKE")
        .env_remove("QTFLOW_VSDEVCMD_BAT")
        .env_remove("VSDEVCMD_BAT")
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["doctor", "--json", "--no-probe"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let json: Value = serde_json::from_slice(&output).expect("valid JSON");
    let dirs = json["discoveredBuildDirs"].as_array().expect("dirs");

    assert_eq!(dirs.len(), 2);
    assert!(dirs.iter().any(|dir| {
        dir["path"] == "build"
            && dir["buildType"] == "Debug"
            && dir["generator"] == "Ninja"
            && dir["multiConfig"] == false
            && dir["provenance"] == "other"
            && dir["role"] == "debug"
    }));
    assert!(dirs.iter().any(|dir| {
        dir["path"] == "build-release" && dir["buildType"] == "Release" && dir["role"] == "release"
    }));
}

#[test]
fn doctor_json_reports_build_dir_ambiguity_and_provenance() {
    let temp = tempfile::tempdir().expect("tempdir");
    std::fs::write(
        temp.path().join("CMakeLists.txt"),
        "cmake_minimum_required(VERSION 3.20)\n",
    )
    .expect("write CMakeLists");
    write_cache(temp.path(), "build", "Debug", "Ninja");
    write_vs_cache(temp.path(), "out/build/debug", "Debug", "Ninja");

    let output = Command::cargo_bin("qtflow")
        .expect("binary")
        .env_remove("QTFLOW_CONFIG")
        .env_remove("QTFLOW_PROFILE")
        .env_remove("QTFLOW_CMAKE")
        .env_remove("QTFLOW_CTEST")
        .env_remove("QTFLOW_NINJA")
        .env_remove("QTFLOW_QMAKE")
        .env_remove("QTFLOW_VSDEVCMD_BAT")
        .env_remove("VSDEVCMD_BAT")
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["doctor", "--json", "--no-probe"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let json: Value = serde_json::from_slice(&output).expect("valid JSON");
    let dirs = json["discoveredBuildDirs"].as_array().expect("dirs");

    assert!(dirs.iter().any(|dir| {
        dir["path"] == "build" && dir["role"] == "debug" && dir["provenance"] == "other"
    }));
    assert!(dirs.iter().any(|dir| {
        dir["path"] == "out/build/debug"
            && dir["role"].is_null()
            && dir["provenance"] == "visualStudio"
    }));
    assert_eq!(
        json["buildDirWarnings"],
        serde_json::json!([{
            "role": "debug",
            "chosen": "build",
            "alternates": ["out/build/debug"],
            "hint": "--build-dir-debug <path>"
        }])
    );
}

#[test]
fn doctor_text_reports_build_dir_ambiguity_with_vs_tag() {
    let temp = tempfile::tempdir().expect("tempdir");
    std::fs::write(
        temp.path().join("CMakeLists.txt"),
        "cmake_minimum_required(VERSION 3.20)\n",
    )
    .expect("write CMakeLists");
    write_cache(temp.path(), "build", "Debug", "Ninja");
    write_vs_cache(temp.path(), "out/build/debug", "Debug", "Ninja");

    Command::cargo_bin("qtflow")
        .expect("binary")
        .env_remove("QTFLOW_CONFIG")
        .env_remove("QTFLOW_PROFILE")
        .env_remove("QTFLOW_CMAKE")
        .env_remove("QTFLOW_CTEST")
        .env_remove("QTFLOW_NINJA")
        .env_remove("QTFLOW_QMAKE")
        .env_remove("QTFLOW_VSDEVCMD_BAT")
        .env_remove("VSDEVCMD_BAT")
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["doctor", "--no-probe"])
        .assert()
        .success()
        .stdout(predicate::str::contains(
            "warning: multiple debug build dirs found: build (chosen), out/build/debug [VS]; override with --build-dir-debug <path>",
        ));
}

#[test]
fn doctor_warns_when_profile_preset_is_not_in_presets_file() {
    let temp = tempfile::tempdir().expect("tempdir");
    std::fs::write(
        temp.path().join("CMakeLists.txt"),
        "cmake_minimum_required(VERSION 3.20)\n",
    )
    .expect("write CMakeLists");
    std::fs::write(
        temp.path().join("CMakePresets.json"),
        r#"{"version": 6, "configurePresets": [{"name": "Other"}]}"#,
    )
    .expect("write presets");

    Command::cargo_bin("qtflow")
        .expect("binary")
        .env_remove("QTFLOW_CONFIG")
        .env_remove("QTFLOW_PROFILE")
        .env_remove("QTFLOW_CMAKE")
        .env_remove("QTFLOW_CTEST")
        .env_remove("QTFLOW_NINJA")
        .env_remove("QTFLOW_QMAKE")
        .env_remove("QTFLOW_VSDEVCMD_BAT")
        .env_remove("VSDEVCMD_BAT")
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["doctor", "--no-probe"])
        .assert()
        .success()
        .stdout(predicate::str::contains(
            "warning: configured preset 'Qt-Debug'",
        ));
}

#[test]
fn doctor_does_not_warn_for_file_defined_profile_omitting_preset() {
    let temp = tempfile::tempdir().expect("tempdir");
    std::fs::write(
        temp.path().join("CMakeLists.txt"),
        "cmake_minimum_required(VERSION 3.20)\n",
    )
    .expect("write CMakeLists");
    std::fs::write(
        temp.path().join("CMakePresets.json"),
        r#"{"version": 6, "configurePresets": [{"name": "Other"}]}"#,
    )
    .expect("write presets");
    std::fs::write(
        temp.path().join(".qtflow.toml"),
        r#"
default_profile = "debug"

[profiles.debug]
build_dir = "build"
generator = "Ninja"
ctest_args = ["--output-on-failure"]

[profiles.release]
build_dir = "build-release"
generator = "Ninja"
ctest_args = ["--output-on-failure"]
"#,
    )
    .expect("write config");

    Command::cargo_bin("qtflow")
        .expect("binary")
        .env_remove("QTFLOW_CONFIG")
        .env_remove("QTFLOW_PROFILE")
        .env_remove("QTFLOW_CMAKE")
        .env_remove("QTFLOW_CTEST")
        .env_remove("QTFLOW_NINJA")
        .env_remove("QTFLOW_QMAKE")
        .env_remove("QTFLOW_VSDEVCMD_BAT")
        .env_remove("VSDEVCMD_BAT")
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["doctor", "--no-probe"])
        .assert()
        .success()
        .stdout(predicate::str::contains("Preset: <none>"))
        .stdout(predicate::str::contains("Qt-Debug").not())
        .stdout(predicate::str::contains("configured preset").not());
}
