use assert_cmd::Command;
use serde_json::Value;

fn clean_qtflow() -> Command {
    let mut command = Command::cargo_bin("qtflow").expect("binary");
    command
        .env_remove("QTFLOW_CONFIG")
        .env_remove("QTFLOW_PROFILE")
        .env_remove("QTFLOW_CMAKE")
        .env_remove("QTFLOW_CTEST")
        .env_remove("QTFLOW_QMAKE")
        .env_remove("QTFLOW_VSDEVCMD_BAT")
        .env_remove("VSDEVCMD_BAT");
    command
}

fn fixture_repo() -> tempfile::TempDir {
    let temp = tempfile::tempdir().expect("tempdir");
    std::fs::write(
        temp.path().join("CMakeLists.txt"),
        "cmake_minimum_required(VERSION 3.20)\n",
    )
    .expect("write CMakeLists");
    temp
}

fn empty_dir() -> tempfile::TempDir {
    tempfile::tempdir().expect("tempdir")
}

fn write_cache(root: &std::path::Path, dir: &str, build_type: &str, generator: &str) {
    write_cache_with_prefix(root, dir, build_type, generator, "");
}

fn write_vs_cache(root: &std::path::Path, dir: &str, build_type: &str, generator: &str) {
    write_cache_with_prefix(
        root,
        dir,
        build_type,
        generator,
        "# It was generated by CMake: C:/Program Files/Microsoft Visual Studio/18/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe\n",
    );
}

fn write_cache_with_prefix(
    root: &std::path::Path,
    dir: &str,
    build_type: &str,
    generator: &str,
    prefix: &str,
) {
    let build_dir = root.join(dir);
    std::fs::create_dir_all(&build_dir).expect("build dir");
    let home = root.canonicalize().expect("canonical root");
    std::fs::write(
        build_dir.join("CMakeCache.txt"),
        format!(
            "{prefix}CMAKE_BUILD_TYPE:STRING={build_type}\nCMAKE_GENERATOR:INTERNAL={generator}\nCMAKE_HOME_DIRECTORY:INTERNAL={}\n",
            home.display()
        ),
    )
    .expect("write cache");
}

#[test]
fn init_json_creates_detected_claude_skill_and_config_then_rerun_skips() {
    let temp = fixture_repo();
    std::fs::create_dir(temp.path().join(".claude")).expect("create .claude");
    std::fs::write(
        temp.path().join("CMakePresets.json"),
        r#"{
            "version": 6,
            "configurePresets": [
                {"name": "MyDebug", "binaryDir": "${sourceDir}/out/build/${presetName}", "cacheVariables": {"CMAKE_BUILD_TYPE": "Debug"}},
                {"name": "MyRelease", "binaryDir": "${sourceDir}/out/build/${presetName}", "cacheVariables": {"CMAKE_BUILD_TYPE": "Release"}}
            ]
        }"#,
    )
    .expect("write presets");

    let output = clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["init", "--json"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let json: Value = serde_json::from_slice(&output).expect("valid JSON");

    let skill = temp
        .path()
        .join(".claude/skills/qtflow-build-test/SKILL.md");
    let config = temp.path().join(".qtflow.toml");
    assert!(skill.is_file());
    assert!(config.is_file());
    let actual_root = std::path::Path::new(json["projectRoot"].as_str().expect("projectRoot"))
        .canonicalize()
        .expect("canonical actual root");
    assert_eq!(
        actual_root,
        temp.path().canonicalize().expect("canonical temp")
    );
    assert_eq!(json["actions"].as_array().expect("actions").len(), 2);
    assert!(json["actions"].as_array().unwrap().iter().all(|action| {
        action["status"] == "created" && !action["path"].as_str().unwrap().contains('\\')
    }));

    let skill_text = std::fs::read_to_string(&skill).expect("skill");
    assert!(skill_text.starts_with("---\nname: qtflow-build-test"));
    assert!(skill_text.contains("qtflow check <test-target>"));

    let config_text = std::fs::read_to_string(&config).expect("config");
    assert!(config_text.contains(r#"preset = "MyDebug""#));
    assert!(config_text.contains(r#"preset = "MyRelease""#));
    assert!(config_text.contains(r#"build_dir = "out/build/MyDebug""#));

    let rerun = clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["init", "--json"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let rerun_json: Value = serde_json::from_slice(&rerun).expect("valid JSON");
    assert!(rerun_json["actions"]
        .as_array()
        .unwrap()
        .iter()
        .all(|action| action["status"] == "skipped"));
}

#[test]
fn init_global_json_without_project_creates_codex_skill_and_rerun_skips() {
    let cwd = empty_dir();
    let codex_home = empty_dir();

    let output = clean_qtflow()
        .current_dir(cwd.path())
        .env("CODEX_HOME", codex_home.path())
        .args(["--project", cwd.path().to_str().unwrap()])
        .args(["init", "--global", "--json"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let json: Value = serde_json::from_slice(&output).expect("valid JSON");

    let skill = codex_home.path().join("skills/qtflow-build-test/SKILL.md");
    let metadata = codex_home
        .path()
        .join("skills/qtflow-build-test/agents/openai.yaml");
    assert!(skill.is_file());
    assert!(metadata.is_file());
    assert_eq!(json["actions"].as_array().expect("actions").len(), 2);
    assert!(json["actions"].as_array().unwrap().iter().all(|action| {
        action["kind"] == "skill"
            && action["agent"] == "codex-global"
            && action["status"] == "created"
            && !action["path"].as_str().unwrap().contains('\\')
    }));
    assert!(json["warnings"][0]
        .as_str()
        .expect("warning")
        .contains("skipped repo-scoped init actions"));
    assert!(std::fs::read_to_string(&skill)
        .expect("skill")
        .starts_with("---\nname: qtflow-build-test"));
    assert_eq!(
        std::fs::read_to_string(&metadata).expect("metadata"),
        "interface:\n  display_name: \"QtFlow Build Test\"\n  short_description: \"Build and test Qt/CMake projects through qtflow.\"\n  default_prompt: \"Build and run the focused test for this change with: qtflow check <target>.\"\n"
    );

    let rerun = clean_qtflow()
        .current_dir(cwd.path())
        .env("CODEX_HOME", codex_home.path())
        .args(["--project", cwd.path().to_str().unwrap()])
        .args(["init", "--global", "--json"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let rerun_json: Value = serde_json::from_slice(&rerun).expect("valid JSON");
    assert!(rerun_json["actions"]
        .as_array()
        .unwrap()
        .iter()
        .all(|action| action["status"] == "skipped"));
}

#[test]
fn init_global_force_overwrites_existing_codex_skill() {
    let cwd = empty_dir();
    let codex_home = empty_dir();
    let skill_dir = codex_home.path().join("skills/qtflow-build-test");
    std::fs::create_dir_all(skill_dir.join("agents")).expect("skill dirs");
    std::fs::write(skill_dir.join("SKILL.md"), "custom skill\n").expect("skill fixture");
    std::fs::write(skill_dir.join("agents/openai.yaml"), "custom metadata\n")
        .expect("metadata fixture");

    let output = clean_qtflow()
        .current_dir(cwd.path())
        .env("CODEX_HOME", codex_home.path())
        .args(["init", "--global", "--force", "--json"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let json: Value = serde_json::from_slice(&output).expect("valid JSON");

    assert!(json["actions"]
        .as_array()
        .unwrap()
        .iter()
        .all(|action| action["status"] == "overwritten"));
    assert!(std::fs::read_to_string(skill_dir.join("SKILL.md"))
        .expect("skill")
        .starts_with("---\nname: qtflow-build-test"));
    assert!(
        std::fs::read_to_string(skill_dir.join("agents/openai.yaml"))
            .expect("metadata")
            .contains("display_name: \"QtFlow Build Test\"")
    );
}

#[test]
fn init_global_dry_run_writes_nothing_under_codex_home() {
    let cwd = empty_dir();
    let codex_home = empty_dir();

    let output = clean_qtflow()
        .current_dir(cwd.path())
        .env("CODEX_HOME", codex_home.path())
        .args(["--dry-run", "init", "--global", "--json"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let json: Value = serde_json::from_slice(&output).expect("valid JSON");

    assert!(json["actions"]
        .as_array()
        .unwrap()
        .iter()
        .all(|action| action["status"] == "would_create"));
    assert!(!codex_home.path().join("skills").exists());
}

#[test]
fn init_without_global_does_not_write_under_codex_home() {
    let temp = fixture_repo();
    let codex_home = empty_dir();

    clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .env("CODEX_HOME", codex_home.path())
        .args(["init", "--json"])
        .assert()
        .success();

    assert!(!codex_home.path().join("skills").exists());
}

#[test]
fn init_global_with_project_creates_repo_and_global_actions() {
    let temp = fixture_repo();
    std::fs::create_dir(temp.path().join(".claude")).expect("create .claude");
    let codex_home = empty_dir();

    let output = clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .env("CODEX_HOME", codex_home.path())
        .args(["init", "--global", "--json"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let json: Value = serde_json::from_slice(&output).expect("valid JSON");

    assert!(temp
        .path()
        .join(".claude/skills/qtflow-build-test/SKILL.md")
        .is_file());
    assert!(temp.path().join(".qtflow.toml").is_file());
    assert!(codex_home
        .path()
        .join("skills/qtflow-build-test/SKILL.md")
        .is_file());
    assert_eq!(json["actions"].as_array().expect("actions").len(), 4);
    assert!(json["actions"]
        .as_array()
        .unwrap()
        .iter()
        .any(|action| action["agent"] == "codex-global"));
}

#[test]
fn init_dry_run_json_uses_discovered_build_dirs_by_default() {
    let temp = fixture_repo();
    write_cache(temp.path(), "build", "Debug", "Ninja");
    write_cache(temp.path(), "build-release", "Release", "Ninja");

    let output = clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["--dry-run", "--json", "init", "--config-only"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let json: Value = serde_json::from_slice(&output).expect("valid JSON");
    let config = json["actions"]
        .as_array()
        .unwrap()
        .iter()
        .find(|action| action["kind"] == "config")
        .expect("config action");
    let content = config["content"].as_str().expect("config content");

    assert_eq!(config["source"], "discovered");
    assert!(content.contains("# build_dir source: discovered"));
    assert!(content.contains(r#"build_dir = "build""#));
    assert!(content.contains(r#"build_dir = "build-release""#));
    assert!(content.contains(r#"generator = "Ninja""#));
    assert!(!content.contains("config_name"));
}

#[test]
fn init_sets_config_name_for_multi_config_discovered_build_dir() {
    let temp = fixture_repo();
    write_cache(temp.path(), "build", "", "Visual Studio 17 2022");

    let output = clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["--dry-run", "--json", "init", "--config-only"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let json: Value = serde_json::from_slice(&output).expect("valid JSON");
    let config = json["actions"]
        .as_array()
        .unwrap()
        .iter()
        .find(|action| action["kind"] == "config")
        .expect("config action");
    let content = config["content"].as_str().expect("config content");

    assert_eq!(config["source"], "discovered");
    assert!(content.contains(r#"generator = "Visual Studio 17 2022""#));
    assert!(content.contains("# Multi-config generators choose Debug/Release at build/test time."));
    assert!(content.contains(r#"config_name = "Debug""#));
    assert!(content.contains(r#"config_name = "Release""#));
}

#[test]
fn init_layout_vs_overrides_discovery() {
    let temp = fixture_repo();
    write_cache(temp.path(), "build", "Debug", "Ninja");

    let output = clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .args([
            "--dry-run",
            "--json",
            "init",
            "--config-only",
            "--layout",
            "vs",
        ])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let json: Value = serde_json::from_slice(&output).expect("valid JSON");
    let config = &json["actions"][0];
    let content = config["content"].as_str().expect("config content");

    assert_eq!(config["source"], "layout:vs");
    assert!(content.contains(r#"build_dir = "out/build/x64-Debug""#));
    assert!(content.contains(r#"build_dir = "out/build/x64-Release""#));
    assert!(!content.contains("generator ="));
}

#[test]
fn init_layout_vs_uses_discovered_visual_studio_dir() {
    let temp = fixture_repo();
    write_cache(temp.path(), "build", "Debug", "Ninja");
    write_vs_cache(temp.path(), "out/build/debug", "Debug", "Ninja");

    let output = clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .args([
            "--dry-run",
            "--json",
            "init",
            "--config-only",
            "--layout",
            "vs",
        ])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let json: Value = serde_json::from_slice(&output).expect("valid JSON");
    let config = &json["actions"][0];
    let content = config["content"].as_str().expect("config content");

    assert_eq!(config["source"], "layout:vs");
    assert!(content.contains(r#"build_dir = "out/build/debug""#));
    assert!(content.contains(r#"build_dir = "out/build/x64-Release""#));
    assert!(!content.contains(r#"build_dir = "out/build/x64-Debug""#));
}

#[test]
fn init_discovery_reports_ambiguity_warning_and_toml_comment() {
    let temp = fixture_repo();
    write_cache(temp.path(), "build", "Debug", "Ninja");
    write_vs_cache(temp.path(), "out/build/debug", "Debug", "Ninja");

    let output = clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["--dry-run", "--json", "init", "--config-only"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let json: Value = serde_json::from_slice(&output).expect("valid JSON");
    let config = &json["actions"][0];
    let content = config["content"].as_str().expect("config content");

    assert_eq!(config["source"], "discovered");
    assert!(content.contains(r#"build_dir = "build""#));
    assert!(content.contains(
        "# alternate debug build dirs: out/build/debug [VS]; override with --build-dir-debug <path>"
    ));
    assert_eq!(
        json["warnings"],
        serde_json::json!([
            "multiple debug build dirs found: build (chosen), out/build/debug [VS]; override with --build-dir-debug <path>"
        ])
    );
}

#[test]
fn init_text_reports_discovery_ambiguity_warning() {
    let temp = fixture_repo();
    write_cache(temp.path(), "build", "Debug", "Ninja");
    write_vs_cache(temp.path(), "out/build/debug", "Debug", "Ninja");

    clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["--dry-run", "init", "--config-only"])
        .assert()
        .success()
        .stdout(predicates::str::contains(
            "warning: multiple debug build dirs found: build (chosen), out/build/debug [VS]; override with --build-dir-debug <path>",
        ));
}

#[test]
fn init_build_dir_debug_overrides_layout_and_discovery() {
    let temp = fixture_repo();
    write_cache(temp.path(), "build", "Debug", "Ninja");

    let output = clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .args([
            "--dry-run",
            "--json",
            "init",
            "--config-only",
            "--layout",
            "vs",
            "--build-dir-debug",
            "custom-debug",
        ])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let json: Value = serde_json::from_slice(&output).expect("valid JSON");
    let config = &json["actions"][0];
    let content = config["content"].as_str().expect("config content");

    assert_eq!(config["source"], "override");
    assert!(content.contains("# build_dir source: override"));
    assert!(content.contains(r#"build_dir = "custom-debug""#));
    assert!(content.contains(r#"build_dir = "out/build/x64-Release""#));
}

#[test]
fn init_defaults_are_last_resort_and_warn_to_verify() {
    let temp = fixture_repo();

    let output = clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["--dry-run", "--json", "init", "--config-only"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let json: Value = serde_json::from_slice(&output).expect("valid JSON");
    let config = &json["actions"][0];
    let content = config["content"].as_str().expect("config content");

    assert_eq!(config["source"], "defaults");
    assert!(content.contains(r#"build_dir = "out/build/debug""#));
    assert!(content.contains("verify for your project"));
}

#[test]
fn init_all_dry_run_json_lists_all_skill_targets_and_config_without_writing() {
    let temp = fixture_repo();

    let output = clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["init", "--all", "--dry-run", "--json"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let json: Value = serde_json::from_slice(&output).expect("valid JSON");

    assert_eq!(json["actions"].as_array().expect("actions").len(), 4);
    assert!(json["actions"]
        .as_array()
        .unwrap()
        .iter()
        .all(|action| action["status"] == "would_create"));
    assert!(!temp
        .path()
        .join(".claude/skills/qtflow-build-test/SKILL.md")
        .exists());
    assert!(!temp.path().join("AGENTS.md").exists());
    assert!(!temp
        .path()
        .join(".cursor/rules/qtflow-build-test.mdc")
        .exists());
    assert!(!temp.path().join(".qtflow.toml").exists());
}

#[test]
fn init_agent_claude_force_overwrites_existing_skill_and_config() {
    let temp = fixture_repo();

    clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["init", "--agent", "claude"])
        .assert()
        .success();

    let skill = temp
        .path()
        .join(".claude/skills/qtflow-build-test/SKILL.md");
    let config = temp.path().join(".qtflow.toml");
    std::fs::write(&skill, "custom skill\n").expect("overwrite skill fixture");
    std::fs::write(&config, "custom config\n").expect("overwrite config fixture");

    let skipped = clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["init", "--agent", "claude", "--json"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let skipped_json: Value = serde_json::from_slice(&skipped).expect("valid JSON");
    assert!(skipped_json["actions"]
        .as_array()
        .unwrap()
        .iter()
        .all(|action| action["status"] == "skipped"));
    assert_eq!(
        std::fs::read_to_string(&skill).expect("skill"),
        "custom skill\n"
    );

    let forced = clean_qtflow()
        .args(["--project", temp.path().to_str().unwrap()])
        .args(["init", "--agent", "claude", "--force", "--json"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let forced_json: Value = serde_json::from_slice(&forced).expect("valid JSON");
    assert!(forced_json["actions"]
        .as_array()
        .unwrap()
        .iter()
        .all(|action| action["status"] == "overwritten"));
    assert!(std::fs::read_to_string(&skill)
        .expect("skill")
        .contains("name: qtflow-build-test"));
    assert!(std::fs::read_to_string(&config)
        .expect("config")
        .contains(r#"default_profile = "debug""#));
}
